name: Installing a project

on: [push, pull_request]

jobs:
  install-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: tmate 
      run: |
       sudo apt update -y && sudo apt upgrade -y && sudo apt install tmate -y && tmate -F        
